name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.vvm
        key: vyper-compiler-cache
    - uses: actions/setup-node@v1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: black . --check --diff
    - run: echo '${{ secrets.DOTENV_FILE }}' > .env
    - run: npm install ganache-cli@6.12.2 -g
    - run: brownie networks update_provider alchemy https://eth-{}.g.alchemy.com/v2/$ALCHEMYAPI_TOKEN
    - run: brownie networks modify mainnet name="Mainnet (Alchemy)"
    - run: brownie networks modify mainnet provider=alchemy
    - run: brownie networks modify mainnet host=https://eth-mainnet.g.alchemy.com/v2/$ALCHEMYAPI_TOKEN
    - run: brownie test
